/* lang-en.js - English translations */

export const en = {
    // Sidebar Menu
    addSensor: "Add Sensor",
    searchPlaceholder: "Type to search...",
    clearAll: "Clear sensor list",
    addCard: "Card +",
    copyYaml: "Copy YAML for dashboard",
    saveView: "Save view",
    listEmpty: "List empty.",
    layout: "Layout (View)",
    combined: "Combined",
    split: "Split (Grid)",
    mixed: "Mixed (Both)",
    showStats: "Show statistics",
    donutSidebar: "Donut Sidebar",
    zoomLevel: "Zoom Level",
    gridColumns: "Grid Columns",
    lineSmoothing: "Line Smoothing (0-5)",
    chartType: "Chart Type (Global):",
    line: "Line (Curve)",
    bar: "Bar (Chart)",
    doughnut: "Doughnut (Distribution)",
    stepped: "Stepped",
    scatter: "Scatter (Points)",
    stackedArea: "Stacked Area",
    threshold1: "Reference Line 1 (Value):",
    threshold2: "Reference Line 2 (Value):",
    yMinLabel: "Y-Axis Min",
    yMaxLabel: "Y-Axis Max",
    yMinTitle: "Minimum Y-axis value. Leave empty for autoscale.",
    yMaxTitle: "Maximum Y-axis value. Leave empty for autoscale.",
    autoPlaceholder: "auto",
    autoScale: "Auto-Scale (W ➡ kW)",
    compareYear: "Compare w/ prev. Year",
    fillArea: "Fill area",
    hideAxisLabels: "Hide axis labels",
    hideGrid: "Hide gridlines",
    dateFormat: "Date format",
    dateFormatDMY: "Day.Month (31.12)",
    dateFormatMDY: "Month/Day (12/31)",
    stackedBars: "Stacked Bars",
    timePeriodMode: "Time Period Mode:",
    relative: "Relative",
    calendar: "Calendar",
    resetZoom: "🔍 Reset Zoom",
    savedViews: "Saved Views",

    // Time periods
    lastHour: "Last 1 Hour",
    last3Hours: "Last 3 Hours",
    last6Hours: "Last 6 Hours",
    last12Hours: "Last 12 Hours",
    last24Hours: "Last 24 Hours",
    last48Hours: "Last 48 Hours",
    last7Days: "Last 7 Days",
    last30Days: "Last 30 Days (Month)",
    last3Months: "Last 3 Months",
    lastYear: "Last Year",
    from: "From:",
    to: "To:",

    // Stat labels
    min: "Min",
    max: "Max",
    avg: "Avg",
    current: "CURRENT",
    sum: "SUM",

    // Modal texts
    codeExport: "Code Export",
    yamlHint: "This code creates a card (yaml - copy for dashboard).",
    copy: "Copy",
    copySuccess: "Copied successfully!",
    jsonHint: 'Here you can find the JSON code for the <b>detailed-charts-views.js</b> file. (See Wiki!)',
    customCardImport: "Custom Card Import",
    importHint: "Paste the YAML code of your custom card here.",
    addCardBtn: "Add Card",

    // Alerts & errors
    copyFailed: "Copy failed.",
    noSensorsSelected: "No sensors selected.",
    sensorAlreadyInList: "Sensor is already in the list.",
    addSensorsFirst: "Please add sensors first.",
    viewNamePrompt: "Name for this LOCAL view:",
    deleteViewConfirm: "Really delete view?",
    globalViewCantDelete: "Global views can only be deleted in the JS file.",
    clearAllConfirm: "Delete all sensors from the list?",
    endDateAfterStart: "End date must be after start date.",
    scatterOnly24h: "Scatter only <= 24h.",
    renameSensorPrompt: "New name for the sensor:",

    // Tooltips & titles
    moveHandle: "Move",
    showValues: "Show values",
    monochromeHighlight: "Highlight Min/Max (Monochrome)",
    collapseSidebar: "Collapse sidebar",
    openMenu: "Open menu",
    homeAssistantMenu: "Home Assistant Menu",
    selectColor: "Select color",
    deleteList: "Delete sensor list",
    addCustomCard: "Add custom card",
    clickToRename: "Click to rename: ",
    globalView: "Global view (in file)",
    delete: "Delete",
    show: "Show",
    hide: "Hide",
    remove: "Remove",
    noViewsSaved: "None saved.",
    error: "Error",
    criticalError: "Error: ",
    loading: "Loading...",

    // Editor specific
    visual: "Visual",
    yaml: "YAML",
    presentation: "Presentation",
    timePeriod: "Time Period",
    options: "Options",
    sensors: "Sensors",
    chartTypeLabel: "Chart Type",
    layoutLabel: "Layout",
    zoomLabel: "Zoom",
    columnsLabel: "Columns",
    thresholdLabel: "Reference Line (Value)",
    modeLabel: "Mode",
    windowLabel: "Window",
    startLabel: "Start",
    endLabel: "End",
    fillAreaLabel: "Fill area",
    statisticsLabel: "Statistics",
    sensorLabel: "Sensor",
    addSensorBtn: "+ ADD SENSOR"
};
